/**
 * Contains raw, umpcompressed, text from a research paper on water in cells.
 * To be injected as context in certain api routes.
 * @author Christopher Curtis
 */
const expertContext = {
    "role": "system",
    "content": `BELOW FOLLOWS THE CONTENT OF A RESEARCH PAPER. USE THIS TO ANSWER ANY QUESTIONS ABOUT CELLS. CLEARLY GIVE INFORMATION TAKEN FROM THIS ARTICLE IN EVERY ANSWER YOU GIVE.
    Abstract
    Liquid water is a highly versatile material. Although it is formed from the tiniest of molecules, it can shape and control biomolecules. The hydrogen-bonding properties of water are crucial to this versatility, as they allow water to execute an intricate three-dimensional 'ballet', exchanging partners while retaining complex order and enduring effects. Water can generate small active clusters and macroscopic assemblies, which can both transmit information on different scales.
    Main
    It is surely time for water to take up its rightful position as the most important and active of all biological molecules, and leave behind the perception that its influence is inconsequential and its presence can be safely disregarded. Liquid water is not a 'bit player' in the theatre of life — it's the headline act. Although reminders of its central importance have been published regularly, although sparsely, over the past century (TIMELINE), the surges in interest that they generate have always fallen back, making way for the 'glitzier', and less ephemeral, structures and properties of other biomolecules such as proteins and nucleic acids. Even today, much of the published material that concerns biological molecules ignores the central role of water in life's machinery. Recently, however, its place as the principal and most versatile player in cell and molecular biology has become clearer.
    Timeline | A brief history of biological water science
    In bulk liquid water, each water molecule not only forms up to four tetrahedrally directed hydrogen bonds with neighbouring water molecules, each molecule can also establish dipole and induced dipole interactions with other molecules (Fig. 1). Such water clusters give liquid water a heterogeneous character that can change with different physical and environmental conditions. The atoms of biomolecules can replace any or all of the links around each water molecule, which affects the structuring of adjacent water molecules and biomolecular groups as well as secondarily linked molecules and distant parts of the biomolecules. Such water molecules can be bound to the surfaces of biomolecules by stronger or weaker forces than their average bulk-phase interaction forces. Either way, they exchange places with other water molecules on a timescale of about 1–100 picoseconds1, and this exchange depends more on the local topography and exposure to competing water molecules than on the strength of their binding. This rapid exchange of partners allows the surface shape of a biomolecule to change but does not significantly change other effects of hydration such as the net direction and strength of the hydrogen bonding.
    Representative structures of water clusters in liquid water are shown. a | A tetrahedrally coordinated water molecule (marked with an asterisk) in an open-hydrogen-bonded, low-density structure. All of the hydrogen bonds are shown as being linear. However, although linear hydrogen bonds are the lowest energy structures, there will be considerable variation. Open structures such as this one can be extended to form extensive, almost isotropic networks. b | A water molecule (marked with an asterisk) is tetrahedrally coordinated to four other water molecules by means of hydrogen bonds, but is also equally close to three non-bonded water molecules that belong to another hydrogen-bonded cluster. These non-bonded interactions are formed from multiple dipoles and induced dipoles. Such clusters have greater entropy and raised enthalpy, and result in high-density local structuring. Actual structural changes in liquid water that are approximated by the conversion between these structural forms have been shown to occur at low temperatures42 and high pressures43, and are thought to be responsible for the extraordinarily anomalous changes that occur in the physical properties of water upon temperature change (see Sixty-three Anomalies of Water in the Further information). However, the question of whether water functions more as a one-state or a two-state system still has to be definitively answered. The atom colouring is: hydrogen, white; and oxygen, red.
    Full size image
    Through the high density of liquid water's compliant, yet strong, hydrogen bonds, it controls protein folding, structure and activity2. It determines the twisting of the DNA double helix3 and the recognition of the DNA sequence4. As the medium for biological processes, it can change and affect them in an instant, slowing them down at one moment, speeding them up at another, while constantly and rapidly transferring information from one place to another, both near and far. Water can function as individual isolated molecules, small clusters, much larger networks or as liquid phases that can have different 'personalities'. Water clusters show great diversity both in their structure and function, with their localized structures being determined by the free energy of bonding and non-bonding contacts5. Despite a clear, consistent and growing message that has been drawn from wide-ranging phenomena, unambiguous confirmation of the presence of particular water clusters remains elusive. This is because most experimental and theoretical techniques cannot observe large-scale clustering and only describe the fleeting environment around individual molecules6,7. In addition, simulations can give results that are based on incomplete sampling, and the resolving power of many experiments is limited by time and space averaging. Indeed, neither diffraction8 nor NMR studies on pure water show any evidence of organized clustering, due either to methodological shortcomings or to the real absence of such clusters.
    
    This article presents evidence for only some of the wide-ranging and complex issues that surround the biological activity of water, and it offers only a glimpse of reality. It covers water's controlling influence over protein and nucleic-acid structure and function, as well as over cellular activity. For deeper analyses, the reader is directed to the reference list and the Further information.
    
    The effects of water on proteins
    
    Water is an integral part of many biomolecules. In particular, protein–water interactions establish and mould the free-energy landscape that governs the folding, structure, stability and activity of proteins9, as is discussed in the following subsections.
    
    Protein folding. Proteins fold rapidly into well defined three-dimensional shapes that depend on the primary sequence of their amino acids. For this to be possible, the folding-energy landscape must consist of a multidimensional funnel with only small energy barriers that can be easily overcome by the available thermal energy (Fig. 2). This requires a mechanism that involves flexible, exchangeable and extensible linkages, and water-mediated hydrogen bonding is ideally suited for this purpose. It is therefore surprising that it has been proposed only recently that protein folding is mediated and guided by aqueous solvation10. Most protein folding occurs with water hydrating the peptide backbone and precisely manoeuvring the backbone through its secondary and supersecondary structural assembly towards its ultimate and unique active structure. Only late in structural development is water squeezed out by cooperative peptide hydrogen-bonding interactions from the more hydrophobic areas towards the more hydrophilic ones. Although water is implicitly involved and implicit water models are used in protein-structure prediction to reduce the computational overhead, empirical methodologies for protein-structure prediction usually fail to include any explicit water molecules. However, it is clear that water needs to be explicitly involved in the more powerful structural prediction methods that realistically follow the biological mechanism of folding11.
    
   Water is not present simply to fill up the available space in and around biological proteins1. Water molecules occupy specific sites and form localized clusters with structures that are determined by their hydrogen-bonding capabilities and the structure of the protein. Water molecules occupy cavities in most globular proteins, where they are present in similar numbers to the numbers of individual amino acids that are present and conserved as an integral part of the protein9. Although these water molecules are exchangeable with external water molecules, many of them are as essential for function as the amino acids9. Surface water molecules are held in place most strongly by charged amino acids12, but are also held in place by other polar groups. 'Slippery water clusters', which have greater freedom for two-dimensional translation along a surface but have restricted molecular rotational mobility, form around exposed hydrophobic areas13. The exchange of surface water, and therefore the persistence of local clustering and the overall flexibility of the system, is controlled by the exposure of the water molecules to the bulk solvent, with greater exposure correlating with greater flexibility and more liberated protein-chain movement9.
    
    Water molecules can bind between the areas of a protein that approach one another but that are not touching, and can transfer surface information between subunits and away towards the bulk (Fig. 3A). As water molecules and their clusters are extremely accommodating in terms of their orientation and spatial distribution, they can lower energy barriers between the energy minima of neighbouring systems. Water can therefore function as a lubricant in that it eases the necessary rearrangements of peptide amide–carbonyl hydrogen bonding during conformational changes, which gives proteins the flexibility they need for their functions14. The hydrogen bonds of water molecules and their clusters can also function as 'mechanical clutches' that transmit relative movement between subunits and domains, depending on the circumstances.
    
    The strength of the water network manages protein dynamics, with greater protein movements occurring in regions that contain many weak, bent or broken hydrogen bonds, because of the presence of more reactive water. Conversely, restricted movement results from the presence of many strong intramolecular aqueous hydrogen bonds. The structural elements that are most exposed to the bulk aqueous media are the least restricted12. The water network links secondary structural elements in the protein and therefore determines not only the fine detail of the structure of a protein, but also which particular molecular vibrations are preferred16.
    
    Protein–ligand interactions. Ordered water molecules at the surfaces of and between biomolecules frequently mediate binding interactions. Water-induced effects can be large and decisive in the selection of the best binding site19. The displacement of bound water molecules from their surface hydration sites often compensates energetically for the formation of direct interactions between biomolecules. There is normally a close relationship between the enthalpic loss and entropic gain of the water molecules that are being displaced and the enthalpic gain and entropic loss of the protein–ligand interaction that is forming, which eases both binding and release20. However, water molecules can remain in place when a new interaction is formed (Fig. 3B), and they, together with peripheral hydrating linkages, can affect the specificity, stereochemistry and thermodynamics of the binding process19. The energetic optimization of hydrogen-bonded networks (including their entropic consequences) that involve a protein, water and a ligand is an intrinsic part of all molecular recognition processes that involve binding proteins and enzymes.
    
    Water in proton and electron transfer
    
    Ordered water molecules that connect donor and acceptor sites can facilitate both proton-transfer processes and electron-transfer reactions. In both cases, the transfer is faster when the linking water molecules are more strongly hydrogen bonded.
    
    Water in proton transfer. There is an extraordinary process, commonly referred to as the Grotthuss mechanism, whereby protons can move speedily in an aqueous environment21. Because transfer occurs between pools that contain low concentrations (∼10−7 M) of protons, conventional diffusion would be extremely slow, because it depends on concentration gradients. By contrast, the Grotthuss mechanism is most efficient in neutral solutions21. Following the addition of a proton to one end of a hydrogen-bonded chain (often referred to as a 'water wire'), hydrogen-bond flipping down the chain releases a different but identical proton at the other end of the water wire. Protons therefore move fastest when an ordered one-dimensional hydrogen-bonded chain facilitates their movement21. A common structural theme among proteins that are involved in proton translocation is a string of water molecules in a hydrophilic cavity that is lined with polar amino acids. Thermal fluctuations that involve these polar amino acids modulate proton transfer by rocking the water molecules. So, the polarization of the hydrogen bonding varies with the closing and opening of the hydrogen-bonded distances, which facilitates proton transfer (Fig. 4A). Water wires are so efficient at transferring protons that they are deliberately disrupted in aquaporin molecules, which allow the single-file translocation of water molecules through membranes. Halfway through these water-transfer channels, water molecules are intentionally reorientated to prevent sequential hydrogen bonding and the resulting facilitated proton transfer22.
    
    The average strength of aqueous interactions with nucleic acids is far greater than that with proteins due to the highly ionic character of nucleic acids24. Although the importance of water is often overlooked, both DNA structure and the crucial recognition of its sequence are reliant on aqueous interactions, with the DNA helix expanding and contracting depending on its hydration status3. Water hydrates both the major and minor grooves of DNA by forming links with the polar atoms at the edges of base pairs, and the orientation of the water molecules depends on the bases and their sequence. The hydration in the minor groove has a complex pattern that includes water hexagons in the initial spine of hydration, secondary hydration, and hydration out as far as the fourth aqueous shell25. This sequence-dependent hydration, which extends to the rim of the grooves, can function as a 'hydration fingerprint' for a given DNA sequence. This enables proteins to sense the base sequence from the outside of the grooves, and allows the rapid and lubricated sensing of the DNA sequence4. The weak binding of proteins to DNA involves mainly the secondary hydration, which allows proteins to slide along the DNA in a manner that is facilitated by the remaining primary hydration water molecules. On encountering specific sites, specialized proteins bind strongly to the DNA, and this is necessary for the processing of genetic information. Proteins do this by releasing and replacing some of the bound water molecules, which compensates for the entropic cost of protein binding.
    
    Cellular water and cell activity
    
    Cellular water. Although some NMR26 and most, if not all, molecular dynamics studies27 show that water outside the inner hydration layer around biomolecules is predominantly unaffected by the biomolecules, other work indicates that water inside cells behaves differently from water outside28. For example, the viscosity of intracellular water is higher and its capability to diffuse is lower, as has been noted by NMR29. This is not simply due to the presence of different solutes or the existence of extended surfaces, but seems to be a more complex consequence of a combination of factors. Indeed, convincing arguments have been put forward that propose that the intracellular milieu is a gel30, a liquid crystal31 or consists of extensively polarized aqueous structuring32. Cells are crowded places, and a high proportion of water is associated with biomolecular interactions and is osmotically unresponsive33. In this environment, small changes in protein conformations can tie up more water, which further reduces diffusive processes, or can release significant amounts of water, which increases the fluidity and activity of the intracellular environment34. Aqueous solutions can form separate, but still fully aqueous, phases depending on the solutes that are present. Such phases consist of low-density water with more extensive hydrogen bonding or high-density water that has fewer and more-bent hydrogen bonds35. As such phases have differing hydration characteristics, reactivities and metabolic capabilities, it is clear that such macroscopic structuring can have an important role in cellular activity. For example, coherent phase microscopy images of cyanobacterial cells and spores, which are responsive to refractive index and size changes, are sensitive to variations of their metabolic states. This might indicate changes in the hydration status, although the effect might be entirely due to membrane effects36.
    
    Cancer cells contain more free water than normal cells, and the degree of malignancy increases with the degree of cell hydration. It follows that intracellular hydration might be a primary factor in carcinogenesis37. This could be because increased hydration facilitates the acceleration of intracellular processes, including respiration, which enhances the competitive edge of a cancer cell for using nutrients.
    
    Communication at a distance. Cells contain several molecules, such as cyclic AMP, that function as messengers between biomolecules and turn processes on and off. Although metabolite diffusion is not generally thought to be limiting over small distances38, the rapid response of cells to changing circumstances seems unlikely to be due only to concentration changes that are sensed following simple diffusive processes. Instead, cells possibly benefit from more speedy information transfer. Water is ideally placed and perfectly suited to this function. A simple example of this is the release of protons to water by one biomolecule that influences the behaviour of other non-touching biomolecules39. However, more complex aqueous effects can also be observed. Changes in protein conformations alter the active water content inside cells, which causes water influx or efflux40 and therefore alters the activity of the hydrating water around other biomolecules. In addition, shifts in the equilibria that involve the high concentration of actin molecules and their polymerized chains necessarily alter the compartmentalization of the cells through changes to the cytoskeleton. The extent of the static charged surfaces of actin, tubulin and intermediate filaments might well affect the amount of free water and therefore the metabolic activity of these water molecules in the cell41.`
}

export default expertContext;
